### ISSUE TITLE
Card not showing infos

### ISSUE THREAD

**Issue by provaprova1** [xguitoux/lovelace-bosch-indego-card#1]
Installed by HACS, inserted the minimum configuration entries
even if the entity name is correct (and works properly in the integration), the cards doesn't show any info

entry in entities list:

![image](https://user-images.githubusercontent.com/31503604/128372176-f9ceb5f1-053c-46cf-98b1-bcc1e0957bf5.png)

card configuration:

![image](https://user-images.githubusercontent.com/31503604/128372301-e21c7f77-ce71-4117-90b2-20eced33ff56.png)

Integration states:

![image](https://user-images.githubusercontent.com/31503604/128372513-aad29ea0-7676-46e3-83e1-52cb63b6c21c.png)

**Comment by Fristi10** [comment]
I have exact the same issue

**Comment by xguitoux** [comment]
Hello @provaprova1, can you press F12 in chrome on the webpage displaying the card and look if there are errors displayed in console ? Thank you

**Comment by xguitoux** [comment]
I've made a new release, you had the wrong file version (my bad I pushed the release without even testing it properly first)

**Comment by Fristi10** [comment]
thnx @xguitoux  for the fix!
