### ISSUE TITLE
ha-icon-button not working

### ISSUE THREAD

**Issue by dimitridelanghe** [xguitoux/lovelace-bosch-indego-card#2]
Hi xguitoux,

ha-icon-button has changed from 2021.11
So as this is still in the .js file on the old way, the button icon is not visible anymore.
But the good news is, it's still working!

Is it possible to fix this icon to be visible again?
Here more information
https://github.com/home-assistant/frontend/blob/dev/src/components/ha-icon-button.ts#L10
https://github.com/denysdovhan/vacuum-card/issues/276

**Comment by Djal94** [comment]
> Hi xguitoux,
> 
> ha-icon-button has changed from 2021.11 So as this is still in the .js file on the old way, the button icon is not visible anymore. But the good news is, it's still working!
> 
> Is it possible to fix this icon to be visible again? Here more information https://github.com/home-assistant/frontend/blob/dev/src/components/ha-icon-button.ts#L10 [denysdovhan/vacuum-card#276](https://github.com/denysdovhan/vacuum-card/issues/276)

Could you please post the edit you’ve done ?

**Comment by dimitridelanghe** [comment]
i couldn't get it fixed, but the icons are still there.
if you use F11 u will see it, and the buttons are working.
Just not visible!
